/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ArsipSuratKeluarIndexRouteImport } from './routes/arsip-surat-keluar/index'
import { Route as ArsipSuratMasukIndexRouteImport } from './routes/arsip-surat-masuk/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ListOtoSuratIndexRouteImport } from './routes/list-oto-surat/index'
import { Route as MemoIndexRouteImport } from './routes/memo/index'
import { Route as PengumumanLiburIndexRouteImport } from './routes/pengumuman-libur/index'
import { Route as AdminDisplayIndexRouteImport } from './routes/admin/display/index'
import { Route as AdminUserIndexRouteImport } from './routes/admin/user/index'
import { Route as AdminUserCreateRouteImport } from './routes/admin/user/create'
import { Route as SuratKeluarEksternalCreateRouteImport } from './routes/surat-keluar/eksternal/create'
import { Route as SuratKeluarInternalCreateRouteImport } from './routes/surat-keluar/internal/create'
import { Route as AdminUserEditIdRouteImport } from './routes/admin/user/edit.$id'
import { Route as SuratTugasUmumEditIdRouteImport } from './routes/surat-tugas/umum/edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipSuratKeluarIndexRoute = ArsipSuratKeluarIndexRouteImport.update({
  id: '/arsip-surat-keluar/',
  path: '/arsip-surat-keluar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipSuratMasukIndexRoute = ArsipSuratMasukIndexRouteImport.update({
  id: '/arsip-surat-masuk/',
  path: '/arsip-surat-masuk/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ListOtoSuratIndexRoute = ListOtoSuratIndexRouteImport.update({
  id: '/list-oto-surat/',
  path: '/list-oto-surat/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoIndexRoute = MemoIndexRouteImport.update({
  id: '/memo/',
  path: '/memo/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengumumanLiburIndexRoute = PengumumanLiburIndexRouteImport.update({
  id: '/pengumuman-libur/',
  path: '/pengumuman-libur/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisplayIndexRoute = AdminDisplayIndexRouteImport.update({
  id: '/admin/display/',
  path: '/admin/display/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/admin/user/',
  path: '/admin/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserCreateRoute = AdminUserCreateRouteImport.update({
  id: '/admin/user/create',
  path: '/admin/user/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SuratKeluarEksternalCreateRoute =
  SuratKeluarEksternalCreateRouteImport.update({
    id: '/surat-keluar/eksternal/create',
    path: '/surat-keluar/eksternal/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuratKeluarInternalCreateRoute =
  SuratKeluarInternalCreateRouteImport.update({
    id: '/surat-keluar/internal/create',
    path: '/surat-keluar/internal/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUserEditIdRoute = AdminUserEditIdRouteImport.update({
  id: '/admin/user/edit/$id',
  path: '/admin/user/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuratTugasUmumEditIdRoute = SuratTugasUmumEditIdRouteImport.update({
  id: '/surat-tugas/umum/edit/$id',
  path: '/surat-tugas/umum/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/arsip-surat-keluar/': typeof ArsipSuratKeluarIndexRoute
  '/arsip-surat-masuk/': typeof ArsipSuratMasukIndexRoute
  '/list-oto-surat/': typeof ListOtoSuratIndexRoute
  '/memo/': typeof MemoIndexRoute
  '/pengumuman-libur/': typeof PengumumanLiburIndexRoute
  '/admin/user/create': typeof AdminUserCreateRoute
  '/surat-keluar/eksternal/create': typeof SuratKeluarEksternalCreateRoute
  '/surat-keluar/internal/create': typeof SuratKeluarInternalCreateRoute
  '/admin/display/': typeof AdminDisplayIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/admin/user/edit/$id': typeof AdminUserEditIdRoute
  '/surat-tugas/umum/edit/$id': typeof SuratTugasUmumEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/arsip-surat-keluar': typeof ArsipSuratKeluarIndexRoute
  '/arsip-surat-masuk': typeof ArsipSuratMasukIndexRoute
  '/list-oto-surat': typeof ListOtoSuratIndexRoute
  '/memo': typeof MemoIndexRoute
  '/pengumuman-libur': typeof PengumumanLiburIndexRoute
  '/admin/user/create': typeof AdminUserCreateRoute
  '/surat-keluar/eksternal/create': typeof SuratKeluarEksternalCreateRoute
  '/surat-keluar/internal/create': typeof SuratKeluarInternalCreateRoute
  '/admin/display': typeof AdminDisplayIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
  '/admin/user/edit/$id': typeof AdminUserEditIdRoute
  '/surat-tugas/umum/edit/$id': typeof SuratTugasUmumEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/arsip-surat-keluar/': typeof ArsipSuratKeluarIndexRoute
  '/arsip-surat-masuk/': typeof ArsipSuratMasukIndexRoute
  '/list-oto-surat/': typeof ListOtoSuratIndexRoute
  '/memo/': typeof MemoIndexRoute
  '/pengumuman-libur/': typeof PengumumanLiburIndexRoute
  '/admin/user/create': typeof AdminUserCreateRoute
  '/surat-keluar/eksternal/create': typeof SuratKeluarEksternalCreateRoute
  '/surat-keluar/internal/create': typeof SuratKeluarInternalCreateRoute
  '/admin/display/': typeof AdminDisplayIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/admin/user/edit/$id': typeof AdminUserEditIdRoute
  '/surat-tugas/umum/edit/$id': typeof SuratTugasUmumEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/sign-in'
    | '/arsip-surat-keluar/'
    | '/arsip-surat-masuk/'
    | '/list-oto-surat/'
    | '/memo/'
    | '/pengumuman-libur/'
    | '/admin/user/create'
    | '/surat-keluar/eksternal/create'
    | '/surat-keluar/internal/create'
    | '/admin/display/'
    | '/admin/user/'
    | '/admin/user/edit/$id'
    | '/surat-tugas/umum/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/sign-in'
    | '/arsip-surat-keluar'
    | '/arsip-surat-masuk'
    | '/list-oto-surat'
    | '/memo'
    | '/pengumuman-libur'
    | '/admin/user/create'
    | '/surat-keluar/eksternal/create'
    | '/surat-keluar/internal/create'
    | '/admin/display'
    | '/admin/user'
    | '/admin/user/edit/$id'
    | '/surat-tugas/umum/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/auth/sign-in'
    | '/arsip-surat-keluar/'
    | '/arsip-surat-masuk/'
    | '/list-oto-surat/'
    | '/memo/'
    | '/pengumuman-libur/'
    | '/admin/user/create'
    | '/surat-keluar/eksternal/create'
    | '/surat-keluar/internal/create'
    | '/admin/display/'
    | '/admin/user/'
    | '/admin/user/edit/$id'
    | '/surat-tugas/umum/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ArsipSuratKeluarIndexRoute: typeof ArsipSuratKeluarIndexRoute
  ArsipSuratMasukIndexRoute: typeof ArsipSuratMasukIndexRoute
  ListOtoSuratIndexRoute: typeof ListOtoSuratIndexRoute
  MemoIndexRoute: typeof MemoIndexRoute
  PengumumanLiburIndexRoute: typeof PengumumanLiburIndexRoute
  AdminUserCreateRoute: typeof AdminUserCreateRoute
  SuratKeluarEksternalCreateRoute: typeof SuratKeluarEksternalCreateRoute
  SuratKeluarInternalCreateRoute: typeof SuratKeluarInternalCreateRoute
  AdminDisplayIndexRoute: typeof AdminDisplayIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
  AdminUserEditIdRoute: typeof AdminUserEditIdRoute
  SuratTugasUmumEditIdRoute: typeof SuratTugasUmumEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip-surat-keluar/': {
      id: '/arsip-surat-keluar/'
      path: '/arsip-surat-keluar'
      fullPath: '/arsip-surat-keluar/'
      preLoaderRoute: typeof ArsipSuratKeluarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip-surat-masuk/': {
      id: '/arsip-surat-masuk/'
      path: '/arsip-surat-masuk'
      fullPath: '/arsip-surat-masuk/'
      preLoaderRoute: typeof ArsipSuratMasukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-oto-surat/': {
      id: '/list-oto-surat/'
      path: '/list-oto-surat'
      fullPath: '/list-oto-surat/'
      preLoaderRoute: typeof ListOtoSuratIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memo/': {
      id: '/memo/'
      path: '/memo'
      fullPath: '/memo/'
      preLoaderRoute: typeof MemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengumuman-libur/': {
      id: '/pengumuman-libur/'
      path: '/pengumuman-libur'
      fullPath: '/pengumuman-libur/'
      preLoaderRoute: typeof PengumumanLiburIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/display/': {
      id: '/admin/display/'
      path: '/admin/display'
      fullPath: '/admin/display/'
      preLoaderRoute: typeof AdminDisplayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/admin/user'
      fullPath: '/admin/user/'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/create': {
      id: '/admin/user/create'
      path: '/admin/user/create'
      fullPath: '/admin/user/create'
      preLoaderRoute: typeof AdminUserCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surat-keluar/eksternal/create': {
      id: '/surat-keluar/eksternal/create'
      path: '/surat-keluar/eksternal/create'
      fullPath: '/surat-keluar/eksternal/create'
      preLoaderRoute: typeof SuratKeluarEksternalCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surat-keluar/internal/create': {
      id: '/surat-keluar/internal/create'
      path: '/surat-keluar/internal/create'
      fullPath: '/surat-keluar/internal/create'
      preLoaderRoute: typeof SuratKeluarInternalCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/edit/$id': {
      id: '/admin/user/edit/$id'
      path: '/admin/user/edit/$id'
      fullPath: '/admin/user/edit/$id'
      preLoaderRoute: typeof AdminUserEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surat-tugas/umum/edit/$id': {
      id: '/surat-tugas/umum/edit/$id'
      path: '/surat-tugas/umum/edit/$id'
      fullPath: '/surat-tugas/umum/edit/$id'
      preLoaderRoute: typeof SuratTugasUmumEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AuthSignInRoute: AuthSignInRoute,
  ArsipSuratKeluarIndexRoute: ArsipSuratKeluarIndexRoute,
  ArsipSuratMasukIndexRoute: ArsipSuratMasukIndexRoute,
  ListOtoSuratIndexRoute: ListOtoSuratIndexRoute,
  MemoIndexRoute: MemoIndexRoute,
  PengumumanLiburIndexRoute: PengumumanLiburIndexRoute,
  AdminUserCreateRoute: AdminUserCreateRoute,
  SuratKeluarEksternalCreateRoute: SuratKeluarEksternalCreateRoute,
  SuratKeluarInternalCreateRoute: SuratKeluarInternalCreateRoute,
  AdminDisplayIndexRoute: AdminDisplayIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
  AdminUserEditIdRoute: AdminUserEditIdRoute,
  SuratTugasUmumEditIdRoute: SuratTugasUmumEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
