import type { RoyaFormData } from "@/types/cab/roya"

export const defaultHapusRoya: RoyaFormData = {
  kantor: "",
  tanggal: new Date(),
  nomor: "",
  bagian: "",
  kode: "",
  bulan: "",
  peringkatHT: "",
  bpnKota: "",
  noAkta: "",
  tglAkta: "",
  notaris: "",
  bentuk: "",
  sertifikat: "",
  noSertifikat: "",
  luas: "",
  noSuratUkur: "",
  tglTerbit: new Date(),
  atasnama: "",
  kelurahan: "",
  kecamatan: "",
  kota: "",
  provinsi: "",
  noSHT: "",
  tglHT: new Date(),
  ttd: [{ nip: "", jabatan: "" }],
}
